#!/bin/python
from sys import argv
from subprocess import *
from urllib import request, parse
import os
import signal

#usage aoc_submit /dirs/run.[cpp,py] -p problem_id, -f

token = open("/home/taylor/code/comp-scripts/web-scripts/aoc_token")
headers = {
    'Accept-Language': 'en-US,en;q=0.8', 
    'Accept-Encoding': 'none', 
    'Accept-Charset': 'ISO-8859-1,utf-8;q=0.7,*;q=0.3', 
    'Connection': 'keep-alive', 'Accept': 'text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8', 
    'User-Agent': 'Mozilla/5.0 (Linux; Android 7.0.1; MotoG4 Build/MPI24.107-55) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/51.0.2704.81 Mobile Safari/537.36',
    "Cookie": f'session={token.read().strip()}'
}
problem_id = argv[2]
year,day = problem_id.split('/')
level = argv[3]
pid = int(argv[4])
f = open(f"/home/taylor/code/aoc/{year}/{day}/1.out")
lines = f.read().strip().split()
ll = lines[-1]
url = f"https://adventofcode.com/{year}/day/{day}/answer"
#data=f"level={level}&answer={ll}"
data={"level":level,
      "answer":ll}
req = request.Request(url, headers = headers)
res = request.urlopen(req, data = parse.urlencode(data).encode())

#response = requests.get(url, headers=headers, data=parse.urlencode(data))
h=res.read().decode('utf-8')
h=h.replace('href="/', 'href="https://adventofcode.com/')
f=open("/tmp/aoc.html", 'w')
f.write(h)
f.close()
Popen(["google-chrome-stable", "/tmp/aoc.html"], stdout=open("/dev/null", "w"), stderr=open("/dev/null", "w"), preexec_fn=os.setpgrp)

if "That's the right answer!" in h:
    if level == "1":
        os.kill(pid, signal.SIGTERM)
        Popen(["alacritty", "-e", "/home/taylor/code/comp-scripts/comp", "aoc", "2", f"{year}/{day}", "--no-confirm", "--no-term"],stdout=open('/dev/null', 'w'),stderr=open('/dev/null', 'w'), preexec_fn=os.setpgrp)
else:
    pass
