#!/bin/python
from subprocess import *
from sys import argv
import os
script_path = argv[0]
file_path = argv[1]
problem_id = argv[2]
Popen([script_path+".py", file_path, "-p", problem_id, "-f"], stderr=open('/dev/null', 'w'), stdout=open('/dev/null', 'w'), preexec_fn=os.setpgrp)
